### ISSUE TITLE
lowrank approximation to fpca

### ISSUE THREAD

**Issue by spinkney** [michaeljauch/polar#1]
hi michael, stan-dev here! I created a low-rank approximation to the fpca code. It runs much, much faster and gives basically the same results. Let me know if you're interested and we could write up a little technical report. 

Sean

**Comment by michaeljauch** [comment]
Hi Sean, 

Finally saw this message, only three years later. That sounds very useful, and I am interested if you still have the code, etc.

Best,
Michael

**Comment by spinkney** [comment]
Hi I do believe I still have this. Let me look and get back to you. Do you want me to do a pr?

**Comment by michaeljauch** [comment]
Great! Yea, that sounds good.
